spring.application.name=FundooNotesApp

spring.datasource.url=jdbc:mysql://localhost:3306/fundoo_notes_app_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Bhuvi@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=7fK3mP9xQ2vL7sN4aB8cD2eF6g   H9jK4m