spring.application.name=project
spring.datasource.url=jdbc:mysql://localhost:3306/GLA
spring.datasource.username=root
spring.datasource.password=AnushkaSinghal24

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true